os:
  - osx
  - linux
language:
  - c
compiler:
  - gcc
jobs:
  include:
    - stage: "Dev"
      name: "Minishell"
      script: make test_minishell
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libncurses5-dev ; fi
email:
  on_success: never
  on_failure: never
notifications:
  email: false