os:
  - osx
  - linux
language:
  - c
compiler:
  - gcc
script:
  - make test
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libncurses5-dev ; fi
email:
  on_success: never
  on_failure: never
notifications:
  email: false